## Numpy

### Arrays

* Supongamos que deseamos hacer ciertos cálculos algebraicos y necesitamos utilizar vectores y matrices. ¿Como podemos implementarlas en Python? 
    * Podemos utilizar listas 
    * Mucho mejor: con Arrays, objetos definidos en el módulo Numpy  

In [2]:
import numpy as np

a = np.array ([1,2,3])   #conversion de lista en array
b = np.array ( [[1,2,3], [14,5,6], [27,8,9]] )

print(a)
print(b)

#Retornar las dimensiones del np.array
print(f"Dimensión de a: {np.shape(a)}")
print(f"Dimensión de b: {np.shape(b)}")

#Los np.array se pueden particionar e indexar
print(b[1,1])
print(b[0, ]) # Primera fila
print(b[0, 1:3]) 


[1 2 3]
[[ 1  2  3]
 [14  5  6]
 [27  8  9]]
Dimensión de a: (3,)
Dimensión de b: (3, 3)
5
[1 2 3]
[2 3]


Métodos de Numpy Array

In [3]:
m = np.empty ((3,3))     # Retorna una matriz sin inicializar valores (3,3)
m = np.zeros ((5, 5))    # Una matriz cuadrada 5 x 5 llena de ceros
m = np.eye(5)            # Matriz identidad de 5 x 5

c = m.dot(m)             # Multiplicación de dos arrays
#Generación de matrices aleatorias
dim = 2
m = np.random.uniform(0., 100, (dim, dim))


[[16.52095258 49.43688805]
 [17.58653123 70.63257845]]
[16.52095258 49.43688805]
[17.58653123 70.63257845]
